# test 4 travis.yml

language: node_js

node_js:
  - "0.8.14"

env:
  global:
   - secure: "P55fyPdg3XSDuvY1k/W1sUYRWMS87vl/xnQWFkg+NLf5EBO/EBLpY7Rxg6hphVSeQp3IvHQk4mUxfI5Nn3XWZYD1iflEMUYu53lTcDJX5ZQzLFBHKDK6GC1xgRS9NNFsDSYCijOYBeP0gmOOUQcA8lKkoodMy6FZSccGzFcbyS0="
   - secure: "RHZm8aArGvct0H6fKOBSmFFUislqrvHOl5a5FdHdctZDRB7NqJ7EwgPcMohmkf8nLbW3T90ecw+ixfho0WYSTU7WThAXNcZFXLzflhqTi9ZuIAuIumxcg97uxj/5t9dnE+Lx9r5XNQQZqB3RXa8MBzmBPWnFlDWU//I/n3oprLo="
   - secure: "X1spNTPoXngP03qg2cOo+nvP9ifsE5bfx3vMOo1W9zW4GcA3OMaewf2cbuR1Mw1Nc2Uh3REDMaBBAxPUkPTWAQhurUQbC3vA68AwkbFnpCZdCN6XAJ+n2s3f09O+ugVsxwci5ycwkASS0iFsyrjUc3W9fKSnxOS9h1Yk3jBYWAQ="
   - secure: "Y8rpoSv/ajwRDIxkWhVUc9K+8Clh3nT8KIDUP6oMqpf4av6puN2it3WuZ6bdHar8e7UvuMy/sPfJQlUL4kZbM2cTRT846OeCayYM+aOL+8nNEaexnpt5PkLhCdrIspoinfKPXkqMLXe4hiMY5STJZR/ELDkee1NHKsE/kDn6qDM="
   - secure: "BAhUEizElhNFNRDqv3EMIxRIb9fy28t+2/nohTszNHmyWs48+++UqTUAVPcR19uk/XKrO56HRozhk/7ex+b64nexpbR3bxfxdNQXBJcKll+r641zdByD7yB1v+yymg4M4bMwNDVmz0xHutV56E4Umw1HEYEd6i/dgcHKwpLqkrA="

install:
  - git checkout master
  - gem install sass
  - BRANCH_NAME=build-$TRAVIS_BRANCH/`eval date +%Y-%m-%d"T"%H-%M-%S`
  - TIME_STR=`eval date`
  - git checkout -b $BRANCH_NAME
  - npm install -g grunt-cli
  - npm install

script:
  - grunt travis
  
after_script:
  - git config --global user.email "$EMAIL"
  - git config --global user.name "$USER_NAME"
  - git remote add github https://$USER_NAME:$PASSWORD@github.com/$USER_NAME/DEP2.git
  - echo -e '\n\n!/app/src/css/*\n!/app/src/js/*\n!/app/app.html\n!/app/app_*.html\n!/app/dist/*' >> .gitignore
  - git add .
  - git commit -m "Travis CI build on $TIME_STR"
  - git push github $BRANCH_NAME
  - git config http.postBuffer 109715200
  - wget https://s3.amazonaws.com/ovivo-beanstalk/AWSbean.tar.gz
  - tar xfvz AWSbean.tar.gz
  - export PATH=$PATH:$PWD/AWS-ElasticBeanstalk-CLI-2.5.1/eb/linux/python2.7
  - eb init -I $AWSAKEY -S $AWSSKEY -a ovivo-oskar -e oskar-env --region "eu-west-1" -s "64bit Amazon Linux running Node.js"
  - eb branch
  - eb start -f
  - git aws.push

branches:
  only:
    - master
