language: node_js

node_js:
  - "0.8.14"

env:
  global:
    - secure: "THIWPLRobMlM5daCZbJeOSjLLlc1MXwWlHKnZ/QiZkmMB+YThmScAj9Mof3anB15fAoOyOzgrREZ5fcwG/25y8UGRqvfm8MI7v6YO7yrwS8Emk/M/S7oTiq2EFDD9ixM3hJ2dWWlQC/w+KYqT7aWNJ+DNXS3nC9Ta7ypFGU2E8E="
    - secure: "FKclWhuVXX5MJHlvwebc9r1dsvtyqk1e8pvOI7ope7B7WLdLyxmhMPqnxXj+Ase5g1Dq/49nOK0khi8NH0DVupv9/qA/hjqPeAGeFxRRxnD8q2lbgSfqPiKJDtFzCfFByHAkw+qcOmVouNe08sIbdt+8KmiTXrxZMC4zv8UeX2I="
    - secure: "Eos5/VOoTbO84mzdB5tFjfK/jNOKjcfZ7aoz3AFkbBHY95mlDJS5CBc75PoWynpt6NfRUmdaHzL1897jHxHreMzNReakWjhXuEGA9DC4MA9f8zKNze5k9CuzmdCnwrNuQy26Gsrn++7PwRaMFdCw3q6LvSIWfXUCykkKvm77/Bk="
    - secure: "OA4ABEnlKkRYtvpwdd6bsXtAjC9oA5sHjb400SAxFL+7QjLLdrLVLhoVu2PGuuGv1KmMYcmQcpV4ypX+cX5cz3WJivT6sNFwaPZi2nCM67gvtz5JdZ3NHlvaT+ZpOvQ5WtKRW+6yfMQi0SkgIIeSCu7n5SO40vl/t5MM9xZNYCo="
    - secure: "ND1pDi31lNjgXDLsBhRwVS948iDnbPLDtwh4PfH8XBkjtidEwRZzoZY4RmD9Er0erTIa51UnHHRwVhDdKrzMthSNfpxVTvy1r/GYXEoAcrJnX42IPUi23QWCre0MHruMfK/VwarxU61AEDWMmwkmkefXl7e1HOUu+jDC/KSgmyM="

install:
  - git checkout master
  - gem install sass
  - BRANCH_NAME=build-$TRAVIS_BRANCH/`eval date +%Y-%m-%d"T"%H-%M-%S`
  - TIME_STR=`eval date`
  - git checkout -b $BRANCH_NAME
  - npm install -g grunt-cli
  - npm install

script:
  - grunt travis
  
after_script:
  - git config --global user.email "$EMAIL"
  - git config --global user.name "$USER_NAME"
  - git remote add github https://eur00t:$PASSWORD@github.com/Ovivo/desktop-employee-planner.git
  - echo -e '\n\n!/app/src/css/*\n!/app/src/js/*\n!/app/app.html\n!/app/app_*.html\n!/app/dist/*' >> .gitignore
  - git add .
  - git commit -m "Travis CI build on $TIME_STR"
  - git push github $BRANCH_NAME
  - git config http.postBuffer 109715200
  - wget https://s3.amazonaws.com/ovivo-beanstalk/AWSbean.tar.gz
  - tar xfvz AWSbean.tar.gz
  - export PATH=$PATH:$PWD/AWS-ElasticBeanstalk-CLI-2.5.1/eb/linux/python2.7
  - eb init -I $AWSAKEY -S $AWSSKEY -a desktop-employee -e ovivo-desktop-employee --region "eu-west-1" -s "64bit Amazon Linux running Node.js"
  - eb branch
  - eb start -f
  - git aws.push

branches:
  only:
    - master