language: node_js

node_js:
  - "0.8.14"

env:
  global:
    - secure: "hIoJ3T0ETQICdb/dc7slq/+794/2rxhASZ4xyipm4IUC0APLBIEyanfzXJd7\nsNX3IDcHyXSxOBK+Ut0y6ydPMqmbxTceAn3JOScg/h5XnjhTeeluP8zjB8LL\nhDFUTX6IR8kGIgAYC/KV3xcCV7IUNUpy6tVyI3vrNm4FL8nlRME="

install:
  - npm install -g grunt-cli
  - cd app
  - npm install
  - cd ../

script:
  - cd app
  - grunt
  - cd ../
  
after_script:
  - git config --global user.email "$EMAIL"
  - git remote add azure https://eur00t@desktop-employee.scm.azurewebsites.net/desktop-employee.git
  - git add .
  - git commit -m "Travis CI build"
  - git push azure master