language: node_js
node_js:
  - "0.8.14"
install:
  - npm install -g grunt-cli
  - cd app
  - npm install
  - cd ../
script:
  - cd app
  - grunt
  - cd ../
  
after_script:
  - git add remote azure https://eur00t@desktop-employee.scm.azurewebsites.net/desktop-employee.git
  - git add .
  - git commit -m "Travis CI build"
  - git push azure master