language: node_js

node_js:
  - "0.8.14"

env:
  global:
    - secure: "hIoJ3T0ETQICdb/dc7slq/+794/2rxhASZ4xyipm4IUC0APLBIEyanfzXJd7\nsNX3IDcHyXSxOBK+Ut0y6ydPMqmbxTceAn3JOScg/h5XnjhTeeluP8zjB8LL\nhDFUTX6IR8kGIgAYC/KV3xcCV7IUNUpy6tVyI3vrNm4FL8nlRME="
    - secure: "IbMKdst5S2nD6VlOgoc4eJ1LOX736kRX/4hKRRNt0xEBeJvpgFP81ey/PKYP\nHwabfg198eO7jR+4Ajg4rTOvlBKRH8nhR34HC1ZK+j7enZpbNXWn9/aEwrCS\nuqJGf+1yiVrGN/tvpLONvRi4TVUUDXXQWfIwy6C32qop4vdyKbs="
    - secure: "go91wOY/iKi3ThKdELqwvDY6PhDpKeSZGNGRu4PTLq8gJi78YfHLZoSqgGea\nYtrTTTPDBL9rZbPcs8eyZ5rVTOJEYE5xb5o02DwQAOkgKiPW01fRAanHlDOv\n76qtryPiEg3JhV2DeuQy7LCH1rKVfqZ4oePJGUVZCI4dvUf2g6U="
    - secure: "OA4ABEnlKkRYtvpwdd6bsXtAjC9oA5sHjb400SAxFL+7QjLLdrLVLhoVu2PGuuGv1KmMYcmQcpV4ypX+cX5cz3WJivT6sNFwaPZi2nCM67gvtz5JdZ3NHlvaT+ZpOvQ5WtKRW+6yfMQi0SkgIIeSCu7n5SO40vl/t5MM9xZNYCo="
    - secure: "ND1pDi31lNjgXDLsBhRwVS948iDnbPLDtwh4PfH8XBkjtidEwRZzoZY4RmD9Er0erTIa51UnHHRwVhDdKrzMthSNfpxVTvy1r/GYXEoAcrJnX42IPUi23QWCre0MHruMfK/VwarxU61AEDWMmwkmkefXl7e1HOUu+jDC/KSgmyM="

install:
  - git checkout master
  - gem install sass
  - BRANCH_NAME=build-$TRAVIS_BRANCH/`eval date +%Y-%m-%d"T"%H-%M-%S`
  - TIME_STR=`eval date`
  - git checkout -b $BRANCH_NAME
  - npm install -g grunt-cli
  - npm install

script:
  - grunt travis
  
after_script:
  - git config --global user.email "$EMAIL"
  - git config --global user.name "$USER_NAME"
  - git remote add github https://eur00t:$PASSWORD@github.com/Ovivo/desktop-employee-planner.git
  - echo -e '\n\n!/app/src/css/*\n!/app/src/js/*\n!/app/app.html\n!/app/app_*.html\n!/app/dist/*' >> .gitignore
  - git add .
  - git commit -m "Travis CI build on $TIME_STR"
  - git push github $BRANCH_NAME
  - wget https://s3.amazonaws.com/ovivo-beanstalk/AWSbean.tar.gz
  - tar xfvz AWSbean.tar.gz
  - export PATH=$PATH:$PWD/AWS-ElasticBeanstalk-CLI-2.5.1/eb/linux/python2.7
  - eb init -I $AWSAKEY -S $AWSSKEY -a desktop-employee -e development --region "eu-west-1" -s "64bit Amazon Linux running Node.js"
  - eb start -f

branches:
  only:
    - master