language: node_js

node_js:
  - "0.8.14"

env:
  global:
    - secure: "hIoJ3T0ETQICdb/dc7slq/+794/2rxhASZ4xyipm4IUC0APLBIEyanfzXJd7\nsNX3IDcHyXSxOBK+Ut0y6ydPMqmbxTceAn3JOScg/h5XnjhTeeluP8zjB8LL\nhDFUTX6IR8kGIgAYC/KV3xcCV7IUNUpy6tVyI3vrNm4FL8nlRME="
    - secure: "IbMKdst5S2nD6VlOgoc4eJ1LOX736kRX/4hKRRNt0xEBeJvpgFP81ey/PKYP\nHwabfg198eO7jR+4Ajg4rTOvlBKRH8nhR34HC1ZK+j7enZpbNXWn9/aEwrCS\nuqJGf+1yiVrGN/tvpLONvRi4TVUUDXXQWfIwy6C32qop4vdyKbs="
    - secure: "go91wOY/iKi3ThKdELqwvDY6PhDpKeSZGNGRu4PTLq8gJi78YfHLZoSqgGea\nYtrTTTPDBL9rZbPcs8eyZ5rVTOJEYE5xb5o02DwQAOkgKiPW01fRAanHlDOv\n76qtryPiEg3JhV2DeuQy7LCH1rKVfqZ4oePJGUVZCI4dvUf2g6U="

install:
  - git checkout master
  - npm install -g grunt-cli
  - cd app
  - npm install
  - cd ../

script:
  - cd app
  - grunt travis
  - cd ../
  
after_script:
  - git config --global user.email "$EMAIL"
  - git config --global user.name "$USER_NAME"
  - git remote add azure https://eur00t:$PASSWORD@desktop-employee.scm.azurewebsites.net/desktop-employee.git
  - git add .
  - git commit -m "Travis CI build"
  - git push -f azure master

branches:
  only:
    - master